CREATE DATABASE Inventario_IT
GO

USE Inventario_IT
GO

-- 1. ROL
CREATE TABLE ROL (
    IdRol INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Descripcion VARCHAR(50) NULL,
    FechaRegistro DATETIME NULL CONSTRAINT DF_ROL_FechaRegistro DEFAULT GETDATE()
);
GO

-- 2. ESTADO
CREATE TABLE ESTADO (
    IdEstado INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Descripcion VARCHAR(100) NULL,
    FechaRegistro DATETIME NULL CONSTRAINT DF_ESTADO_FechaRegistro DEFAULT GETDATE()
);
GO

-- 3. MARCA
CREATE TABLE MARCA (
    IdMarca INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Descripcion VARCHAR(100) NULL,
    Estado BIT NULL,
    FechaRegistro DATETIME NULL CONSTRAINT DF_MARCA_FechaRegistro DEFAULT GETDATE()
);
GO

-- 4. NEGOCIO
CREATE TABLE NEGOCIO (
    IdNegocio INT NOT NULL PRIMARY KEY,
    Nombre VARCHAR(60) NULL,
    RUC VARCHAR(60) NULL,
    Direccion VARCHAR(60) NULL,
    Logo VARBINARY(MAX) NULL
);
GO

-- 5. USUARIO (depende de ROL)
CREATE TABLE USUARIO (
    IdUsuario INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Documento VARCHAR(50) NULL,
    NombreCompleto VARCHAR(50) NULL,
    Correo VARCHAR(50) NULL,
    Clave VARCHAR(MAX) NULL,
    IdRol INT NULL,
    Estado BIT NULL,
    FechaRegistro DATETIME NULL CONSTRAINT DF_USUARIO_FechaRegistro DEFAULT GETDATE(),
    NombreUsuario VARCHAR(50) NULL,
    CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (IdRol) REFERENCES ROL (IdRol)
);
GO

-- 6. FARMACIA
CREATE TABLE FARMACIA (
    IdFarmacia INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Codigo VARCHAR(50) NULL,
    Nombre VARCHAR(50) NULL,
    Telefono VARCHAR(50) NULL,
    Estado BIT NULL,
    FechaRegistro DATETIME NULL CONSTRAINT DF_FARMACIA_FechaRegistro DEFAULT GETDATE()
);
GO

-- 7. EQUIPO (depende de ESTADO, MARCA)
CREATE TABLE EQUIPO (
    IdEquipo INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Codigo VARCHAR(50) NULL,
    Nombre VARCHAR(50) NULL,
    Descripcion VARCHAR(50) NULL,
    IdMarca INT NULL,
    Stock INT NOT NULL CONSTRAINT DF_EQUIPO_Stock DEFAULT (0),
    IdEstado INT NULL,
    FechaRegistro DATETIME NULL CONSTRAINT DF_EQUIPO_FechaRegistro DEFAULT GETDATE(),
    CONSTRAINT FK_EQUIPO_ESTADO FOREIGN KEY (IdEstado) REFERENCES ESTADO (IdEstado),
    CONSTRAINT FK_EQUIPO_MARCA FOREIGN KEY (IdMarca) REFERENCES MARCA (IdMarca)
);
GO

-- 8. PERMISO (depende de ROL)
CREATE TABLE PERMISO (
    IdPermiso INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    IdRol INT NULL,
    NombreMenu VARCHAR(100) NULL,
    FechaRegistro DATETIME NULL CONSTRAINT DF_PERMISO_FechaRegistro DEFAULT GETDATE(),
    CONSTRAINT FK_PERMISO_ROL FOREIGN KEY (IdRol) REFERENCES ROL (IdRol)
);
GO

-- 9. REGISTRAR (depende de USUARIO)
CREATE TABLE REGISTRAR (
    IdRegistrar INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    IdUsuario INT NULL,
    TipoDocumento VARCHAR(50) NULL,
    NumeroDocumento VARCHAR(50) NULL,
    FechaRegistro DATETIME NULL CONSTRAINT DF_REGISTRAR_FechaRegistro DEFAULT GETDATE(),
    CONSTRAINT FK_REGISTRAR_USUARIO FOREIGN KEY (IdUsuario) REFERENCES USUARIO (IdUsuario)
);
GO

-- 10. DETALLE_REGISTRAR (depende de EQUIPO, REGISTRAR)
CREATE TABLE DETALLE_REGISTRAR (
    IdDetalleRegistrar INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    IdRegistrar INT NULL,
    IdEquipo INT NULL,
    Cantidad INT NULL,
    FechaRegistro DATETIME NULL CONSTRAINT DF_DETALLEREGISTRAR_FechaRegistro DEFAULT GETDATE(),
    CONSTRAINT FK_DETALLEREGISTRAR_EQUIPO FOREIGN KEY (IdEquipo) REFERENCES EQUIPO (IdEquipo),
    CONSTRAINT FK_DETALLEREGISTRAR_REGISTRAR FOREIGN KEY (IdRegistrar) REFERENCES REGISTRAR (IdRegistrar)
);
GO

-- 11. ACTA (depende de USUARIO, FARMACIA)
CREATE TABLE ACTA (
    IdActa INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    IdUsuario INT NULL,
    TipoDocumento VARCHAR(50) NULL,
    NumeroDocumento VARCHAR(50) NULL,
    Codigo VARCHAR(50) NULL,
    Nombre VARCHAR(100) NULL,
    FechaRegistro DATETIME NULL CONSTRAINT DF_ACTA_FechaRegistro DEFAULT GETDATE(),
    IdFarmacia INT NULL,
    EstadoAutorizacion VARCHAR(20) NULL CONSTRAINT DF_ACTA_EstadoAutorizacion DEFAULT ('PENDIENTE'),
    Estado VARCHAR(20) NULL CONSTRAINT DF_ACTA_Estado DEFAULT ('AUTORIZADO'),
    CONSTRAINT FK_ACTA_USUARIO FOREIGN KEY (IdUsuario) REFERENCES USUARIO (IdUsuario),
    CONSTRAINT FK_ACTA_FARMACIA FOREIGN KEY (IdFarmacia) REFERENCES FARMACIA (IdFarmacia)
);
GO

-- 12. DETALLE_ACTA (depende de ACTA, EQUIPO)
CREATE TABLE DETALLE_ACTA (
    IdDetalleActa INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    IdActa INT NULL,
    IdEquipo INT NULL,
    Cantidad INT NULL,
    FechaRegistro DATETIME NULL CONSTRAINT DF_DETALLEACTA_FechaRegistro DEFAULT GETDATE(),
    NumeroSerial VARCHAR(100) NULL,
    Caja VARCHAR(100) NULL,
    MotivoBaja VARCHAR(MAX) NULL,
    EstadoBaja VARCHAR(50) NULL,
    IdUsuarioAutorizo INT NULL,
    IdUsuarioSolicita INT NULL,
    CONSTRAINT FK_DETALLEACTA_ACTA FOREIGN KEY (IdActa) REFERENCES ACTA (IdActa),
    CONSTRAINT FK_DETALLEACTA_EQUIPO FOREIGN KEY (IdEquipo) REFERENCES EQUIPO (IdEquipo)
);
GO
