CREATE DATABASE Inventario_IT
GO

USE Inventario_IT
GO

-- 1. ROL
CREATE TABLE ROL (
    IdRol INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Descripcion VARCHAR(50) NOT NULL,
    FechaRegistro DATETIME NULL CONSTRAINT DF_ROL_FechaRegistro DEFAULT GETDATE()
);
GO
-- Agregar columna Estado a la tabla ROL
ALTER TABLE ROL
ADD Estado BIT NOT NULL CONSTRAINT DF_ROL_Estado DEFAULT 1;

-- 2. ESTADO
CREATE TABLE ESTADO (
    IdEstado INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Descripcion VARCHAR(100) NULL,
    FechaRegistro DATETIME NULL CONSTRAINT DF_ESTADO_FechaRegistro DEFAULT GETDATE()
);
GO

-- 3. MARCA
CREATE TABLE MARCA (
    IdMarca INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Descripcion VARCHAR(100) NULL,
    Estado BIT NULL,
    FechaRegistro DATETIME NULL CONSTRAINT DF_MARCA_FechaRegistro DEFAULT GETDATE()
);
GO

-- 4. NEGOCIO
CREATE TABLE NEGOCIO (
    IdNegocio INT NOT NULL PRIMARY KEY,
    Nombre VARCHAR(60) NULL,
    RUC VARCHAR(60) NULL,
    Direccion VARCHAR(60) NULL,
    Logo VARBINARY(MAX) NULL
);
GO

-- 5. USUARIO (depende de ROL)
CREATE TABLE USUARIO (
    IdUsuario INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Documento VARCHAR(50) NULL,
    NombreCompleto VARCHAR(50) NULL,
    Correo VARCHAR(50) NULL,
    Clave VARCHAR(MAX) NULL,
    IdRol INT NULL,
    Estado BIT NULL,
    FechaRegistro DATETIME NULL CONSTRAINT DF_USUARIO_FechaRegistro DEFAULT GETDATE(),
    NombreUsuario VARCHAR(50) NULL,
    CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (IdRol) REFERENCES ROL (IdRol)
);
GO

-- 6. FARMACIA
CREATE TABLE FARMACIA (
    IdFarmacia INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Codigo VARCHAR(50) NULL,
    Nombre VARCHAR(50) NULL,
    Telefono VARCHAR(50) NULL,
    Estado BIT NULL,
    FechaRegistro DATETIME NULL CONSTRAINT DF_FARMACIA_FechaRegistro DEFAULT GETDATE()
);
GO

ALTER TABLE FARMACIA
ADD Correo VARCHAR(100) NULL;
GO


-- 7. EQUIPO (depende de ESTADO, MARCA)
CREATE TABLE EQUIPO (
    IdEquipo INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Codigo VARCHAR(50) NULL,
    Nombre VARCHAR(50) NULL,
    Descripcion VARCHAR(50) NULL,
    IdMarca INT NULL,
    Stock INT NOT NULL CONSTRAINT DF_EQUIPO_Stock DEFAULT (0),
    IdEstado INT NULL,
    FechaRegistro DATETIME NULL CONSTRAINT DF_EQUIPO_FechaRegistro DEFAULT GETDATE(),
    CONSTRAINT FK_EQUIPO_ESTADO FOREIGN KEY (IdEstado) REFERENCES ESTADO (IdEstado),
    CONSTRAINT FK_EQUIPO_MARCA FOREIGN KEY (IdMarca) REFERENCES MARCA (IdMarca)
);
GO
-- 8. MODULO O MENU PRINCIPAL
CREATE TABLE MODULO (
    IdModulo INT IDENTITY(1,1) PRIMARY KEY,
    NombreModulo VARCHAR(100) NOT NULL,
	FechaRegistro DATETIME NULL CONSTRAINT DF_MODULO_FechaRegistro DEFAULT GETDATE()
);
GO

-- 9. SUBMENU
CREATE TABLE SUBMENU (
    IdSubMenu INT IDENTITY(1,1) PRIMARY KEY,
    IdModulo INT NOT NULL,
    NombreSubMenu VARCHAR(100) NOT NULL,
	FechaRegistro DATETIME NULL CONSTRAINT DF_SUBMENU_FechaRegistro DEFAULT GETDATE(),
    FOREIGN KEY (IdModulo) REFERENCES MODULO(IdModulo)
);
GO

-- 10. ACCION (botones o acciones dentro de un submenú)
CREATE TABLE ACCION (
    IdAccion INT IDENTITY(1,1) PRIMARY KEY,
	IdModulo INT NULL,
    IdSubMenu INT NULL,
    NombreAccion VARCHAR(100) NOT NULL,
	FechaRegistro DATETIME NULL CONSTRAINT DF_ACCION_FechaRegistro DEFAULT GETDATE(),
    FOREIGN KEY (IdModulo) REFERENCES MODULO(IdModulo),
	FOREIGN KEY (IdSubMenu) REFERENCES SUBMENU(IdSubMenu)
);
GO

-- 11. PERMISO
CREATE TABLE PERMISO (
    IdPermiso INT IDENTITY(1,1) PRIMARY KEY,
    IdRol INT NOT NULL,
    IdModulo INT NULL,
    IdSubMenu INT NULL,
    IdAccion INT NULL,
    FechaRegistro DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (IdRol) REFERENCES ROL(IdRol),
    FOREIGN KEY (IdModulo) REFERENCES MODULO(IdModulo),
    FOREIGN KEY (IdSubMenu) REFERENCES SUBMENU(IdSubMenu),
    FOREIGN KEY (IdAccion) REFERENCES ACCION(IdAccion)
);
GO

-- 12. REGISTRAR (depende de USUARIO)
CREATE TABLE REGISTRAR (
    IdRegistrar INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    IdUsuario INT NULL,
    TipoDocumento VARCHAR(50) NULL,
    NumeroDocumento VARCHAR(50) NULL,
    FechaRegistro DATETIME NULL CONSTRAINT DF_REGISTRAR_FechaRegistro DEFAULT GETDATE(),
    CONSTRAINT FK_REGISTRAR_USUARIO FOREIGN KEY (IdUsuario) REFERENCES USUARIO (IdUsuario)
);
GO

-- 13. DETALLE_REGISTRAR (depende de EQUIPO, REGISTRAR)
CREATE TABLE DETALLE_REGISTRAR (
    IdDetalleRegistrar INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    IdRegistrar INT NULL,
    IdEquipo INT NULL,
    Cantidad INT NULL,
    FechaRegistro DATETIME NULL CONSTRAINT DF_DETALLEREGISTRAR_FechaRegistro DEFAULT GETDATE(),
    CONSTRAINT FK_DETALLEREGISTRAR_EQUIPO FOREIGN KEY (IdEquipo) REFERENCES EQUIPO (IdEquipo),
    CONSTRAINT FK_DETALLEREGISTRAR_REGISTRAR FOREIGN KEY (IdRegistrar) REFERENCES REGISTRAR (IdRegistrar)
);
GO

-- 14. ACTA (depende de USUARIO, FARMACIA)
CREATE TABLE ACTA (
    IdActa INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    IdUsuario INT NULL,
    TipoDocumento VARCHAR(50) NULL,
    NumeroDocumento VARCHAR(50) NULL,
    Codigo VARCHAR(50) NULL,
    Nombre VARCHAR(100) NULL,
    FechaRegistro DATETIME NULL CONSTRAINT DF_ACTA_FechaRegistro DEFAULT GETDATE(),
    IdFarmacia INT NULL,
    EstadoAutorizacion VARCHAR(20) NULL CONSTRAINT DF_ACTA_EstadoAutorizacion DEFAULT ('PENDIENTE'),
    Estado VARCHAR(20) NULL CONSTRAINT DF_ACTA_Estado DEFAULT ('AUTORIZADO'),
    CONSTRAINT FK_ACTA_USUARIO FOREIGN KEY (IdUsuario) REFERENCES USUARIO (IdUsuario),
    CONSTRAINT FK_ACTA_FARMACIA FOREIGN KEY (IdFarmacia) REFERENCES FARMACIA (IdFarmacia)
);
GO



UPDATE ACTA
SET IdUsuarioAutorizo = 1
WHERE EstadoAutorizacion = 'AUTORIZADO';

ALTER TABLE ACTA
ADD IdUsuarioAutorizo INT NULL;
GO

ALTER TABLE ACTA
ADD CONSTRAINT FK_ACTA_USUARIO_AUTORIZO
FOREIGN KEY (IdUsuarioAutorizo) REFERENCES USUARIO(IdUsuario);
GO

-- 15. DETALLE_ACTA (depende de ACTA, EQUIPO)
CREATE TABLE DETALLE_ACTA (
    IdDetalleActa INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    IdActa INT NULL,
    IdEquipo INT NULL,
    Cantidad INT NULL,
    FechaRegistro DATETIME NULL CONSTRAINT DF_DETALLEACTA_FechaRegistro DEFAULT GETDATE(),
    NumeroSerial VARCHAR(100) NULL,
    Caja VARCHAR(100) NULL,
    MotivoBaja VARCHAR(MAX) NULL,
    EstadoBaja VARCHAR(50) NULL,
    IdUsuarioAutorizo INT NULL,
    IdUsuarioSolicita INT NULL,
    CONSTRAINT FK_DETALLEACTA_ACTA FOREIGN KEY (IdActa) REFERENCES ACTA (IdActa),
    CONSTRAINT FK_DETALLEACTA_EQUIPO FOREIGN KEY (IdEquipo) REFERENCES EQUIPO (IdEquipo)
);
GO


CREATE TABLE PRESTAMO (
    IdPrestamo INT IDENTITY(1,1) PRIMARY KEY,
    IdUsuarioSolicita INT NOT NULL,            -- quien solicita el préstamo
    IdUsuarioAutoriza INT NULL,                -- quien autoriza
    IdFarmacia INT NULL,                       -- área o destino temporal
    TipoDocumento VARCHAR(50) NULL,
    NumeroDocumento VARCHAR(50) NULL,
    FechaPrestamo DATETIME DEFAULT GETDATE(),
    FechaDevolucion DATETIME NULL,
    EstadoPrestamo VARCHAR(50) DEFAULT 'PENDIENTE',  -- PENDIENTE, APROBADO, RECHAZADO, DEVUELTO
    Comentario VARCHAR(MAX) NULL,
    CONSTRAINT FK_PRESTAMO_USUARIO_SOL FOREIGN KEY (IdUsuarioSolicita) REFERENCES USUARIO(IdUsuario),
    CONSTRAINT FK_PRESTAMO_USUARIO_AUT FOREIGN KEY (IdUsuarioAutoriza) REFERENCES USUARIO(IdUsuario),
    CONSTRAINT FK_PRESTAMO_FARMACIA FOREIGN KEY (IdFarmacia) REFERENCES FARMACIA(IdFarmacia)
);
GO

CREATE TABLE DETALLE_PRESTAMO (
    IdDetallePrestamo INT IDENTITY(1,1) PRIMARY KEY,
    IdPrestamo INT NOT NULL,
    IdEquipo INT NOT NULL,                     -- obligatorio: para controlar stock
    Cantidad INT NOT NULL CHECK (Cantidad > 0),
    NumeroSerial VARCHAR(100) NULL,
    EstadoDevolucion VARCHAR(50) DEFAULT 'PENDIENTE',  -- PENDIENTE, DEVUELTO, DAÑADO, EXTRAVIADO
    FechaRegistro DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_DETALLEPRESTAMO_PRESTAMO FOREIGN KEY (IdPrestamo) REFERENCES PRESTAMO(IdPrestamo),
    CONSTRAINT FK_DETALLEPRESTAMO_EQUIPO FOREIGN KEY (IdEquipo) REFERENCES EQUIPO(IdEquipo)
);
GO

ALTER TABLE DETALLE_PRESTAMO
ADD IdUsuarioDevuelve INT NULL;

ALTER TABLE DETALLE_PRESTAMO
ADD MotivoBaja VARCHAR(MAX) NULL,
    EstadoBaja VARCHAR(50) NULL;
GO


CREATE TABLE AUDITORIA (
    IdAuditoria INT IDENTITY(1,1) PRIMARY KEY,
    Tabla NVARCHAR(100) NOT NULL,         -- Nombre de la tabla afectada
    Operacion NVARCHAR(10) NOT NULL,      -- INSERT, UPDATE, DELETE
    Usuario NVARCHAR(100) NULL,           -- Usuario que hizo el cambio
    Fecha DATETIME NOT NULL DEFAULT GETDATE(),
    Datos NVARCHAR(MAX) NULL              -- Detalles de los datos afectados
);
GO



-- Indices 
CREATE NONCLUSTERED INDEX IX_DETALLE_REGISTRAR_IdRegistrar ON DETALLE_REGISTRAR(IdRegistrar);
CREATE NONCLUSTERED INDEX IX_EQUIPO_IdEquipo ON EQUIPO(IdEquipo);
